# Generated by Django 3.2.13 on 2023-09-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ListaLebron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top1', models.CharField(max_length=50)),
                ('top2', models.CharField(max_length=50)),
                ('top3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('frase_feitos', models.CharField(max_length=200)),
                ('frase_titulos', models.CharField(max_length=200)),
                ('pontos_totais', models.IntegerField()),
                ('jogador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppDoPedro.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('media_pontos', models.FloatField()),
                ('media_assists', models.FloatField()),
                ('media_rebotes', models.FloatField()),
                ('jogador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppDoPedro.jogador')),
            ],
        ),
    ]
