# Generated by Django 3.2.13 on 2023-09-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDoPedro', '0002_rename_frase_feitos_conquista_frase_feito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medias_Jogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador_1', models.CharField(max_length=70)),
                ('jogador_2', models.CharField(max_length=70)),
                ('jogador_3', models.CharField(max_length=70)),
                ('pontos_media_1', models.FloatField()),
                ('rebotes_media_1', models.FloatField()),
                ('assistencias_media_1', models.FloatField()),
                ('pontos_media_2', models.FloatField()),
                ('rebotes_media_2', models.FloatField()),
                ('assistencias_media_2', models.FloatField()),
                ('pontos_media_3', models.FloatField()),
                ('rebotes_media_3', models.FloatField()),
                ('assistencias_media_3', models.FloatField()),
            ],
        ),
    ]
