# Generated by Django 3.2.13 on 2023-09-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDoPedro', '0003_medias_jogadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top1', models.CharField(max_length=100)),
                ('top2', models.CharField(max_length=100)),
                ('top3', models.CharField(max_length=100)),
                ('my_reasons', models.CharField(max_length=100)),
            ],
        ),
    ]
