# Generated by Django 3.2.13 on 2023-09-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDoPedro', '0004_lista_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lista_Usuario',
            new_name='Lista_Usuarios',
        ),
    ]
