# Generated by Django 3.2.13 on 2023-09-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDoPedro', '0005_rename_lista_usuario_lista_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=50)),
                ('feito_historico', models.CharField(max_length=200)),
                ('pontos_totais', models.PositiveIntegerField()),
                ('colocacao_pts', models.CharField(max_length=50)),
                ('info_titulos', models.CharField(max_length=200)),
                ('media_pts', models.PositiveIntegerField()),
                ('media_assist', models.PositiveIntegerField()),
                ('media_rebs', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('top1', models.ManyToManyField(blank=True, related_name='top1', to='AppDoPedro.Jogadores')),
                ('top2', models.ManyToManyField(blank=True, related_name='top2', to='AppDoPedro.Jogadores')),
                ('top3', models.ManyToManyField(blank=True, related_name='top3', to='AppDoPedro.Jogadores')),
            ],
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='jogador',
        ),
        migrations.RemoveField(
            model_name='estatistica',
            name='jogador',
        ),
        migrations.DeleteModel(
            name='Lista_Usuarios',
        ),
        migrations.DeleteModel(
            name='ListaLebron',
        ),
        migrations.DeleteModel(
            name='Medias_Jogadores',
        ),
        migrations.DeleteModel(
            name='Conquista',
        ),
        migrations.DeleteModel(
            name='Estatistica',
        ),
        migrations.DeleteModel(
            name='Jogador',
        ),
    ]
