# Generated by Django 3.2.13 on 2023-09-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDoPedro', '0006_auto_20230919_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadores',
            name='media_assist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jogadores',
            name='media_pts',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jogadores',
            name='media_rebs',
            field=models.FloatField(),
        ),
    ]
