# Generated by Django 3.2.13 on 2023-10-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDoPedro', '0009_auto_20230920_0341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userlist',
        ),
    ]
